### ISSUE TITLE
Proper Installation procedure using pip

### ISSUE THREAD

**Issue by SuhrudhSarathy** [SuhrudhSarathy/drone_sim#5]
Add a proper installation procedure for using it through pip install

**Comment by acestark12** [comment]
Hey there, I am new to open source. I would like to contribute into this. Could you please brief about this issue?
@SuhrudhSarathy

**Comment by SuhrudhSarathy** [comment]
Hey @acestark12!
So, I am assuming you know about pip(if not take a look at this: https://pip.pypa.io/en/stable/). Every package that can be installed via pip has some specific files like `setup.py` or `requirements.txt` within the package. This helps python to identify and correctly install the package into your local machine so that its available for other files etc. So as a part of this issues, we will have to set those up so that we can do `pip install .` to install the package rather than adding the package to the python path etc.
You can take a look at this: https://betterscientificsoftware.github.io/python-for-hpc/tutorials/python-pypi-packaging/

**Comment by acestark12** [comment]
@SuhrudhSarathy 
Yes, thankfully I know it. So, could you please assign it to me?
